version: "2"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
   web:
     image: ubuntu:16.04
     ports:
       - "3000:3000"
     command: ['/usr/sbin/grafana-server', '-config', '/etc/grafana/grafana.ini', '-homepath', '/usr/share/grafana/']
     dev_overrides:
       environment:
         - "DEBUG=1"
  #
registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
