- name: Spin up aws elb
  hosts: local
  connection: local

  tasks:
    - local_action:
          module: ec2_elb_lb
          name: "{{ elb_name }}"
          state: present
          region: ap-southeast-1
          aws_secret_key: '{{ aws_secret_key }}'
          aws_access_key: '{{ aws_access_key }}'
          zones:
            - ap-southeast-1a
          listeners:
            - protocol: http # options are http, https, ssl, tcp
              load_balancer_port: 80
              instance_port: 80
