satu: 1
dua: 2
  #karena nam[0] and streng terlalu sombong
bilangan: satudua
streng: "put"
spechar: /mu/*/c{}x?
lesto:
  mona: ini
  moni: ono
dicto:
  - nam: chi
    fure: kamuy
  - nam: iru
    fure: uhuy
kosong:
